# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

OneCompOralCpp <- function(inputFrame) {
    .Call('PKADVAN_OneCompOralCpp', PACKAGE = 'PKADVAN', inputFrame)
}

TwoCompOralCpp <- function(inputFrame) {
    .Call('PKADVAN_TwoCompOralCpp', PACKAGE = 'PKADVAN', inputFrame)
}

ThreeCompOralCpp <- function(inputFrame) {
    .Call('PKADVAN_ThreeCompOralCpp', PACKAGE = 'PKADVAN', inputFrame)
}

OneCompFirstOrderAbsOneCompMetabCpp <- function(inputFrame) {
    .Call('PKADVAN_OneCompFirstOrderAbsOneCompMetabCpp', PACKAGE = 'PKADVAN', inputFrame)
}

TwoCompFirstOrderAbsOneCompMetabCpp <- function(inputFrame) {
    .Call('PKADVAN_TwoCompFirstOrderAbsOneCompMetabCpp', PACKAGE = 'PKADVAN', inputFrame)
}

ThreeCompFirstOrderAbsOneCompMetabCpp <- function(inputFrame) {
    .Call('PKADVAN_ThreeCompFirstOrderAbsOneCompMetabCpp', PACKAGE = 'PKADVAN', inputFrame)
}

OneCompIVbolusOneCompMetabCpp <- function(inputFrame) {
    .Call('PKADVAN_OneCompIVbolusOneCompMetabCpp', PACKAGE = 'PKADVAN', inputFrame)
}

TwoCompIVbolusOneCompMetabCpp <- function(inputFrame) {
    .Call('PKADVAN_TwoCompIVbolusOneCompMetabCpp', PACKAGE = 'PKADVAN', inputFrame)
}

ThreeCompIVbolusOneCompMetabCpp <- function(inputFrame) {
    .Call('PKADVAN_ThreeCompIVbolusOneCompMetabCpp', PACKAGE = 'PKADVAN', inputFrame)
}

OneCompIVbolusCpp <- function(inputFrame) {
    .Call('PKADVAN_OneCompIVbolusCpp', PACKAGE = 'PKADVAN', inputFrame)
}

TwoCompIVbolusCpp <- function(inputFrame) {
    .Call('PKADVAN_TwoCompIVbolusCpp', PACKAGE = 'PKADVAN', inputFrame)
}

ThreeCompIVbolusCpp <- function(inputFrame) {
    .Call('PKADVAN_ThreeCompIVbolusCpp', PACKAGE = 'PKADVAN', inputFrame)
}

OneCompIVinfusionCpp <- function(inputFrame) {
    .Call('PKADVAN_OneCompIVinfusionCpp', PACKAGE = 'PKADVAN', inputFrame)
}

TwoCompIVinfusionCpp <- function(inputFrame) {
    .Call('PKADVAN_TwoCompIVinfusionCpp', PACKAGE = 'PKADVAN', inputFrame)
}

ThreeCompIVinfusionCpp <- function(inputFrame) {
    .Call('PKADVAN_ThreeCompIVinfusionCpp', PACKAGE = 'PKADVAN', inputFrame)
}

OneCompIVinfusionOneCompMetabCpp <- function(inputFrame) {
    .Call('PKADVAN_OneCompIVinfusionOneCompMetabCpp', PACKAGE = 'PKADVAN', inputFrame)
}

TwoCompIVinfusionOneCompMetabCpp <- function(inputFrame) {
    .Call('PKADVAN_TwoCompIVinfusionOneCompMetabCpp', PACKAGE = 'PKADVAN', inputFrame)
}

ThreeCompIVinfusionOneCompMetabCpp <- function(inputFrame) {
    .Call('PKADVAN_ThreeCompIVinfusionOneCompMetabCpp', PACKAGE = 'PKADVAN', inputFrame)
}

OneCompOneTransitCpp <- function(inputFrame) {
    .Call('PKADVAN_OneCompOneTransitCpp', PACKAGE = 'PKADVAN', inputFrame)
}

OneCompTwoTransitCpp <- function(inputFrame) {
    .Call('PKADVAN_OneCompTwoTransitCpp', PACKAGE = 'PKADVAN', inputFrame)
}

OneCompThreeTransitCpp <- function(inputFrame) {
    .Call('PKADVAN_OneCompThreeTransitCpp', PACKAGE = 'PKADVAN', inputFrame)
}

OneCompFourTransitCpp <- function(inputFrame) {
    .Call('PKADVAN_OneCompFourTransitCpp', PACKAGE = 'PKADVAN', inputFrame)
}

TwoCompOneTransitCpp <- function(inputFrame) {
    .Call('PKADVAN_TwoCompOneTransitCpp', PACKAGE = 'PKADVAN', inputFrame)
}

TwoCompTwoTransitCpp <- function(inputFrame) {
    .Call('PKADVAN_TwoCompTwoTransitCpp', PACKAGE = 'PKADVAN', inputFrame)
}

TwoCompThreeTransitCpp <- function(inputFrame) {
    .Call('PKADVAN_TwoCompThreeTransitCpp', PACKAGE = 'PKADVAN', inputFrame)
}

TwoCompFourTransitCpp <- function(inputFrame) {
    .Call('PKADVAN_TwoCompFourTransitCpp', PACKAGE = 'PKADVAN', inputFrame)
}

