// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// OneCompOralCpp
DataFrame OneCompOralCpp(DataFrame inputFrame);
RcppExport SEXP PKADVAN_OneCompOralCpp(SEXP inputFrameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type inputFrame(inputFrameSEXP);
    __result = Rcpp::wrap(OneCompOralCpp(inputFrame));
    return __result;
END_RCPP
}
// TwoCompOralCpp
DataFrame TwoCompOralCpp(DataFrame inputFrame);
RcppExport SEXP PKADVAN_TwoCompOralCpp(SEXP inputFrameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type inputFrame(inputFrameSEXP);
    __result = Rcpp::wrap(TwoCompOralCpp(inputFrame));
    return __result;
END_RCPP
}
// ThreeCompOralCpp
DataFrame ThreeCompOralCpp(DataFrame inputFrame);
RcppExport SEXP PKADVAN_ThreeCompOralCpp(SEXP inputFrameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type inputFrame(inputFrameSEXP);
    __result = Rcpp::wrap(ThreeCompOralCpp(inputFrame));
    return __result;
END_RCPP
}
// ThreeCompFirstOrderAbsOneCompMetabCpp
DataFrame ThreeCompFirstOrderAbsOneCompMetabCpp(DataFrame inputFrame);
RcppExport SEXP PKADVAN_ThreeCompFirstOrderAbsOneCompMetabCpp(SEXP inputFrameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type inputFrame(inputFrameSEXP);
    __result = Rcpp::wrap(ThreeCompFirstOrderAbsOneCompMetabCpp(inputFrame));
    return __result;
END_RCPP
}
// OneCompIVbolusCpp
DataFrame OneCompIVbolusCpp(DataFrame inputFrame);
RcppExport SEXP PKADVAN_OneCompIVbolusCpp(SEXP inputFrameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type inputFrame(inputFrameSEXP);
    __result = Rcpp::wrap(OneCompIVbolusCpp(inputFrame));
    return __result;
END_RCPP
}
// TwoCompIVbolusCpp
DataFrame TwoCompIVbolusCpp(DataFrame inputFrame);
RcppExport SEXP PKADVAN_TwoCompIVbolusCpp(SEXP inputFrameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type inputFrame(inputFrameSEXP);
    __result = Rcpp::wrap(TwoCompIVbolusCpp(inputFrame));
    return __result;
END_RCPP
}
// ThreeCompIVbolusCpp
DataFrame ThreeCompIVbolusCpp(DataFrame inputFrame);
RcppExport SEXP PKADVAN_ThreeCompIVbolusCpp(SEXP inputFrameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type inputFrame(inputFrameSEXP);
    __result = Rcpp::wrap(ThreeCompIVbolusCpp(inputFrame));
    return __result;
END_RCPP
}
// ThreeCompIVinfusionOneCompMetabCpp
DataFrame ThreeCompIVinfusionOneCompMetabCpp(DataFrame inputFrame);
RcppExport SEXP PKADVAN_ThreeCompIVinfusionOneCompMetabCpp(SEXP inputFrameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type inputFrame(inputFrameSEXP);
    __result = Rcpp::wrap(ThreeCompIVinfusionOneCompMetabCpp(inputFrame));
    return __result;
END_RCPP
}
// OneCompIVinfusionCpp
DataFrame OneCompIVinfusionCpp(DataFrame inputFrame);
RcppExport SEXP PKADVAN_OneCompIVinfusionCpp(SEXP inputFrameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type inputFrame(inputFrameSEXP);
    __result = Rcpp::wrap(OneCompIVinfusionCpp(inputFrame));
    return __result;
END_RCPP
}
// TwoCompIVinfusionCpp
DataFrame TwoCompIVinfusionCpp(DataFrame inputFrame);
RcppExport SEXP PKADVAN_TwoCompIVinfusionCpp(SEXP inputFrameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type inputFrame(inputFrameSEXP);
    __result = Rcpp::wrap(TwoCompIVinfusionCpp(inputFrame));
    return __result;
END_RCPP
}
// ThreeCompIVinfusionCpp
DataFrame ThreeCompIVinfusionCpp(DataFrame inputFrame);
RcppExport SEXP PKADVAN_ThreeCompIVinfusionCpp(SEXP inputFrameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type inputFrame(inputFrameSEXP);
    __result = Rcpp::wrap(ThreeCompIVinfusionCpp(inputFrame));
    return __result;
END_RCPP
}
// OneCompOneTransitCpp
DataFrame OneCompOneTransitCpp(DataFrame inputFrame);
RcppExport SEXP PKADVAN_OneCompOneTransitCpp(SEXP inputFrameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type inputFrame(inputFrameSEXP);
    __result = Rcpp::wrap(OneCompOneTransitCpp(inputFrame));
    return __result;
END_RCPP
}
// OneCompTwoTransitCpp
DataFrame OneCompTwoTransitCpp(DataFrame inputFrame);
RcppExport SEXP PKADVAN_OneCompTwoTransitCpp(SEXP inputFrameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type inputFrame(inputFrameSEXP);
    __result = Rcpp::wrap(OneCompTwoTransitCpp(inputFrame));
    return __result;
END_RCPP
}
// OneCompThreeTransitCpp
DataFrame OneCompThreeTransitCpp(DataFrame inputFrame);
RcppExport SEXP PKADVAN_OneCompThreeTransitCpp(SEXP inputFrameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type inputFrame(inputFrameSEXP);
    __result = Rcpp::wrap(OneCompThreeTransitCpp(inputFrame));
    return __result;
END_RCPP
}
// OneCompFourTransitCpp
DataFrame OneCompFourTransitCpp(DataFrame inputFrame);
RcppExport SEXP PKADVAN_OneCompFourTransitCpp(SEXP inputFrameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type inputFrame(inputFrameSEXP);
    __result = Rcpp::wrap(OneCompFourTransitCpp(inputFrame));
    return __result;
END_RCPP
}
// TwoCompOneTransitCpp
DataFrame TwoCompOneTransitCpp(DataFrame inputFrame);
RcppExport SEXP PKADVAN_TwoCompOneTransitCpp(SEXP inputFrameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type inputFrame(inputFrameSEXP);
    __result = Rcpp::wrap(TwoCompOneTransitCpp(inputFrame));
    return __result;
END_RCPP
}
// TwoCompTwoTransitCpp
DataFrame TwoCompTwoTransitCpp(DataFrame inputFrame);
RcppExport SEXP PKADVAN_TwoCompTwoTransitCpp(SEXP inputFrameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type inputFrame(inputFrameSEXP);
    __result = Rcpp::wrap(TwoCompTwoTransitCpp(inputFrame));
    return __result;
END_RCPP
}
// TwoCompThreeTransitCpp
DataFrame TwoCompThreeTransitCpp(DataFrame inputFrame);
RcppExport SEXP PKADVAN_TwoCompThreeTransitCpp(SEXP inputFrameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type inputFrame(inputFrameSEXP);
    __result = Rcpp::wrap(TwoCompThreeTransitCpp(inputFrame));
    return __result;
END_RCPP
}
// TwoCompFourTransitCpp
DataFrame TwoCompFourTransitCpp(DataFrame inputFrame);
RcppExport SEXP PKADVAN_TwoCompFourTransitCpp(SEXP inputFrameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type inputFrame(inputFrameSEXP);
    __result = Rcpp::wrap(TwoCompFourTransitCpp(inputFrame));
    return __result;
END_RCPP
}
