---
title: "PKADVAN-introduction"
author: "Ahmad Y Abuhelwa, David J.R Foster, Richard N Upton"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{PKADVAN-introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
## Introduction 
  ADVAN-style analytical solutions for 1, 2, 3 compartment linear pharmacokinetic models of intravenous bolus, infusion,
and first-order absorption have been derived and published by [Abuhelwa et al., 2015](http://www.ncbi.nlm.nih.gov/pubmed/25841670) [1]. The analytical solutions are used to simulate the time-course of drug amounts in the compartments of a pharmacokinetic models and they “advance” the solution of the model from one time point to the next, allowing for any dose or time-varying covariate factors to be accounted for. The ADVAN-style analytical solutions were coded in the R programming language [2] and have been shown to have speed advantages over solutions using differential equation solvers [1]. 

## Aims
The aims of this work were to:

  - Enhance the computational speed of the ADVAN-style analytical functions through coding them in hybrid R/C++ programming languages for faster simulation processing.

  - Present the ADVAN-style analytical functions in an R package, “PKADVAN” package, and make them available for the wider audience.
  
  - Expand the “PKADVAN” package library to include other pharmacokinetic models such as transit first-order absorption and metabolite models.

## Methods
  - The ADVAN-style analytical solutions were derived using Laplace transforms and then were coded in the C++ programming language and integrated into R using the Rcpp package attributes [3].
  
  - The integrated R/C++ ADVAN-style analytical functions were built into an open-source R package (“PKADVAN” package). 
  
  - To assess computational speed, simulations for 1000 subjects using three compartment IV bolus, infusion, and first-order absorption models were performed and compared to relative computational speed of the equivalent R-coded functions. For each subject, two doses were simulated with the evaluations performed at 1 hour time intervals for 2 days.
  
  - All pharmacokinetic models incorporated into the “PKADVAN” package have been validated against the commercially available population pharmacokinetic modelling software NONMEM.

## PKADVAN package
  - A total of 26 pharmacokinetic models were incorporated into the “PKADVAN” package library including the basic models published by Abuhelwa et al [1]. A list of all the models is presented in Table 1.

  - To perform pharmacokinetic simulations using the “PKADVAN” package, two simple steps are required: (1) Supply a NONMEM-style simulation data frame with the individual pharmacokinetic parameters including any covariate effects on the PK parameters (2) Call the “PKADVAN” function of the respective model to process simulations.

  - The NONMEM-style data frame should have the following columns: ID, TIME, AMT, in addition to the individual pharmacokinetic parameters of the respective pharmacokinetic model (e.g., CL, V, Q).
The PKADVAN functions returns the drug amounts in the respective compartments and the individual predicted concentrations (IPRED) in the central compartment of the pharmacokinetic system.
  
  - The PKADVAN functions are capable of simulating arbitrary dosing regimens and can account for time-changing covariate structures; however, covariate effects on respective parameters must be calculated prior processing simulations.

  - All the PKADVAN functions were validated against NONMEM and both outputs were identical. 
Stochastic population pharmacokinetic model simulations using the PKADVAN functions are comparable to NONMEM. An example output using PKADVAN package versus NONMEM is presented in Figure 1.

  - The “PKADVAN” package is available on GitHub and can be downloaded by clicking [here](https://github.com/abuhelwa/PKADVAN_Rpackage). 
  - Users are encouraged to read the package documentation and run the  simulation examples provided with the package.
  
  - Simulations using the integrated R/C++ ADVAN-style analytical solutions were substantially faster (8‑34 times) than the equivalent R-coded functions (Table 2). The relative speed of the integrated R/C++ functions was greater with the more complex models and with more extensive sample time evaluations (Table 2). 

## Applications
  - The PKADVAN package can be used for performing simulations from stochastic population pharmacokinetic models coded in R and incorporated into reactive ‘Shiny’ web applications where speed is important as it allows for simulating larger populations without compromising the reactivity of the Shiny application.

  - The PKADVAN package can be implemented for data fitting, and for calculating confidence and prediction intervals of pharmacokinetic models’ parameters [4].
  
  - The PKADVAN package could be incorporated into an open-source mixed-effect modelling framework to estimate population parameters where speed is always desirable. 


##Conclusions
With its speed advantages and the capacity to handle arbitrary dosing regimens and covariate structures, the “PKADVAN” package is expected to facilitate the investigation of a useful open-source software for modelling and simulating pharmacokinetic data.

## To do list
  - Implement steady-state functionality, as achieved with the SS and II data items in NONMEM. 
  - Implement analytical solutions for combined dosing regimens (e.g., IV bolus plus infusion).
  - Implement the analytical solutions for fitting population PK data


## References
  1. Abuhelwa AY, Foster DJ, Upton RN. 2015. ADVAN-style analytical solutions for common pharmacokinetic models. J Pharmacol Toxicol Methods 73:42-48.
  2. R Core Team. 2014. R: A Language and Environment for Statistical Computing R Foundation for Statistical Computing, Vienna, Austria.
  3. Eddelbuettel D, François R, Allaire J, Chambers J, Bates D, Ushey K. 2011. Rcpp: Seamless R and C++ integration. Journal of Statistical Software 40:1-18.
  4. Kümmel A, Abuhelwa AY, Dingemanse J, Krause A. PECAN, a Shiny application for calculating confidence and prediction intervals for pharmacokinetic and pharmacodynamic models. The twenty-fifth Annual Population Approach Group Europe (PAGE) Meeting. 2016



